### PR TITLE
Project launch templates rework

### PR DESCRIPTION
**Pull request by kgroeneveld**
This rework is based on proposed updated templates originally created by the admins.

This is still a WIP. It breaks operation for all languages but English. But I want to wait for feedback from the LibriVox admins before cleaning up the language files as there will likely be further refinements.

This pull request also includes other improvements to the project launch process such as adding a Copy to Clipboard button to the results page.

### CODE REVIEW

**Comment by notartom** [comment]
We do have a [staging environment](https://forum.librivox.org/viewtopic.php?f=49&t=69859) we can use to have admins test this. I'm currently using it to test your other PRs, but I can leave it with this PR only and have folks play around. I'll make a forum post and/or send an email once that's ready.

**Comment by kgroeneveld** [comment]
I just added a commit to this PR for issue #25. The change doesn't apply without the rest of the commits for this PR and it is all related to the project launch template anyway.

I am really starting to think I need to setup a second dev environment with the older PHP 5.6 to make sure my changes will also work there. Does the live server have ubuntu 16.04 still as mentioned in the ansible instructions? Maybe I will even set it up so the admins can test these changes. Its a fairly big change and I have a feeling there will be a lot of refinement yet.

**Comment by notartom** [comment]
> Does the live server have ubuntu 16.04 still as mentioned in the ansible instructions?

Yes :(

**Comment by kgroeneveld** [comment]
I just added another commit to this PR which fixes a bug where the copyright noticed based on authors year of death was getting dropped if there was no translator. I happened to notice this bug in the code while working on the previous commit for filename formatting. Once again the fix doesn't apply cleanly without the previous commits in this PR.

I also setup an ubuntu 16.04 server today to test these changes in addition to my ubuntu 20.04 setup. It looks good so far. After a bit more testing I will probably get @twinkietoes-on to post the IP address on the LibriVox forum for the admins to try out.

**Comment by notartom** [comment]
> After a bit more testing I will probably get @twinkietoes-on to post the IP address on the LibriVox forum for the admins to try out.

There's already a [forum post](https://forum.librivox.org/viewtopic.php?f=49&t=69859) (though you need an admin-level account to see it) on accessing the staging environment.

**Comment by twinkietoes-on** [comment]
Changes to templates as per the admin comments:

SOLO TEMPLATE:

1. Move the "please don't download" message, MW, & stuff in === to below the general info, above "Intro to Recording" (before or after "Important: Soloist please note"? I don't know)

SOLO/GROUP/DRAMATIC TEMPLATES:

2. Put the quoted items that readers are to say in quote tags (4 instances in solo template, 3 in group, 4 in dramatic)

3. Immediately below the MW, add:

[b]LibriVox recording settings:[/b] mono (1 channel), 44100 Hz sample rate, 128 kbps constant bit rate MP3. See the [url=https://wiki.librivox.org/index.php?title=Tech_Specs]Tech Specs[/url]

WEEKLY/FORTNIGHTLY POETRY TEMPLATES:

4. Below "New to Recording?" and before "Begin your reading", add:

[b]LibriVox recording settings:[/b] mono (1 channel), 44100 Hz sample rate, 128 kbps constant bit rate MP3. See the [url=https://wiki.librivox.org/index.php?title=Tech_Specs]Tech Specs[/url]

5. Swap the "deadline" line with the "check back" line

ALL TEMPLATES:

5. Color MC name blue: [b]MC to select:[/b] [color=#0000FF]xxxx[/color]

**Comment by twinkietoes-on** [comment]
Two newly discovered items:

(1) Line breaks in Summary field: I attempted to add a summary with paragraphs/line breaks. It's as if my Enter button wasn't working. 

(2) After the admin generates the Magic Window, there is no vertical space between the bottom of the MW and the next batch of text. One must add 3 blank lines/line breaks to get the proper vertical spacing. Example on live site: https://forum.librivox.org/viewtopic.php?f=26&t=85085
I'm not sure of a foolproof workaround. We could add two lines of a colored period [color=#E1ECF2].[/color] (the background color of the first post) as a kind of bodge?

**Comment by kgroeneveld** [comment]
>Changes to templates as per the admin comments:
>...

These should now all be part of the updated pull request.
>(1) Line breaks in Summary field: I attempted to add a summary with paragraphs/line breaks. It's as if my Enter key wasn't working.

Turns out this was always like this. It works in the admin page but not project launch. I added a fix for this as well.
>(2) After the admin generates the Magic Window, there is no vertical space between the bottom of the MW and the next batch of text ...

The best way to fix this may be to change the setup of the `[MW]` bbcode in the phpBB config. I added an extra `<br>` at the end of the [MW] code setup in my dev environment and it looks better. The only problem with this approach is you may end up with extra space for anyone who has already manually added a workaround in the existing posts. Although one extra line of blank space probably isn't too bad.

**Comment by kgroeneveld** [comment]
This is getting close now. I just imported the translation changes the admins have been making and also made a couple other small updates. The branch for this PR is now active on my dev server so the admins can give it another quick test. If all goes well I can remove the draft status from the PR and it can hopefully be merged soon.

**Comment by kgroeneveld** [comment]
This is finally ready to go. The majority of it has been running on my test server for a few days now so they admins could test it. The only changes in the past couple days were minor tweaks to some of the translations.

There will likely be further refinements in the long run. But this PR is already getting quite large and it is at a good stopping point for now.

**Pull request merged**
