### PR TITLE
Validator improvements including new check for "_128kb" in filename.

### PR DESCRIPTION
**Pull request by kgroeneveld**
The first commit in this PR addresses #27.

While working on that I found a number of other issues in the validator that were bugging me so this PR includes a couple more commits for some of those issues. It seemed as though I found an endless number of issues and confusingly written code in the validator such that I could spend much more time on it. I tried to keep the changes to a minimum of low risk changes and resist my urge to re-write larger sections of it (and make my own mess)...  maybe another time.

See commit logs for more details on the actual changes.

### CODE REVIEW

**Comment by kgroeneveld** [comment]
After I switched branches in my local git repo I seem be getting an error relating to this PR. I should probably double check what is going on before this gets merged...

**Comment by kgroeneveld** [comment]
>After I switched branches in my local git repo I seem be getting an error relating to this PR. I should probably double check what is going on before this gets merged...

False alarm. When I switched branches I lost an un-commited changed that breaks the validator on PHP 7.4. If I re-instate that change or checkout this exact PR branch on my other dev system with PHP 5.6 it works fine.

**Comment by twinkietoes-on** [comment]
For the record, I have tested this, and it seems to work without breaking anything else. ;)

**Comment by notartom** [comment]
I'm assuming the bitrate has to be 128kpbs, and that has to be reflected in the filename?

**Comment by twinkietoes-on** [comment]
Yes. Archive needs that appended onto the file names in order to identify the MP3s as 128 kbps. Otherwise they're identified as VBR.

**Pull request merged**
