### PR TITLE
Fix image link href in browse catalog title blade.

### PR DESCRIPTION
**Pull request by kgroeneveld**
The second commit does not apply without the first so I made them one pull request even though they are separate (but related) issues.

### CODE REVIEW

**Review by notartom — CHANGES_REQUESTED** [review]
I don't think this commit is necessary at all, looks like all our coverart_thumbnail URLs are for archive.org, and can be updated to HTTP directly in the database:

`artom@librivox:~$ mysql librivox_catalog -e 'select coverart_thumbnail from projects where coverart_thumbnail<>""'  | grep -v archive\\\.org
coverart_thumbnail
artom@librivox:~$`

**Comment by kgroeneveld** [comment]
I dropped the second commit from the PR. (Hopefully I did it correctly, I have never edited a github pull request before.) It probably should have been a separate request anyway.

I agree that it would be good to update all the entries in the data base to be https.  (I even wonder if the data base should include the https:// at all or if that should be inserted at runtime, but that is a bigger change and may not even make sense.) My only concern was that we should then be preventing new entries from having same issue then. My patch was really only meant to be a temporary solution.

**Comment by notartom** [comment]
So where do these http:// links appear in the HTML? They're definitely http:// in the database, but something appears to be translating them to https:// before they hit the view, at least in all the places that I'm looking.

**Comment by kgroeneveld** [comment]
Try going to https://librivox.org/the-30000-bequest-and-other-stories-by-mark-twain/.  Firefox warns about mixed content. If you view the page source you can see the title artwork is `book-cover-large`.  (Assuming you are not running the original version of this PR which converted it to https.)

**Comment by notartom** [comment]
OK - next question is - where is the http:// coming from when it's saved in the database? Because as you've said, doing s/http/https/ in the DB is one thing, but it won't prevent new http:// URLs from being added. I've done a few greps around the codebase, and I can't figure it out. I suspect `coverart_thumbnail` is not being saved explicitly, but rather as an ORM save call, I just don't know where that happens.

**Comment by kgroeneveld** [comment]
>OK - next question is - where is the http:// coming from when it's saved in the database?

Good question. I am not sure exactly myself. I haven't quite figured out the typical flow in CI / LibriVox catalog yet. I think it is input by the user in this view: `application/views/private/administer_projects/add_catalog_item.php`. And I think that form is validated in `application/controllers/private/administer_projects.php`. Maybe it would be a matter of adding another validator similar to the one for Title in that file: `$this->form_validation->set_rules('projectname', 'Title', 'trim|required|xss_clean');`.

There is a reason I started off by just hacking the code to dynamically change the http to https...  I was looking for a quick fix to the security warnings browsers are giving now and I didn't really know how to fix it properly yet. I also was not sure how easy it would be to fix the entries in the existing database. That isn't something I have access to do even if I was confident about how to do it. I guess it could be done with a fairly simple script one could test on a copy of the database.

I wonder how much of the https discussion should be moved to #26 and start a separate PR once we decide on a plan. The other remaining commit in this PR is really a separate issue. In hindsight I regret lumping them together.

**Comment by notartom** [comment]
> I wonder how much of the https discussion should be moved to #26 and start a separate PR once we decide on a plan. The other remaining commit in this PR is really a separate issue. In hindsight I regret lumping them together.

Good point. Let's get this one merged, and carry on the HTTP(S) discussion in #26.

**Pull request merged**
